### PR TITLE
Add quickload wrapper for qt-meta

### PR DESCRIPTION
**Pull request by ryukinix**
(ql-meta:quickload 'trivial-gamekit :dist 'bodge)

### CODE REVIEW

**Review by luksamuk — APPROVED** [review]
Looks good to me. One small thing: if a dist is not installed before the execution of `ql-meta:quickload`, it should be checked beforehand so the dist is removed again after system installation.

**Comment by ryukinix** [comment]
> Looks good to me. One small thing: if a dist is not installed before the execution of `ql-meta:quickload`, it should be checked beforehand so the dist is removed again after system installation.

Right, this makes sense!

**Comment by ryukinix** [comment]
@luksamuk DONE!

**Comment by ryukinix** [comment]
image


Check this shit @luksamuk

**Comment by luksamuk** [comment]
Amazing.

**Pull request merged**
